def get_common_abbreviations() -> set[str]:
    """Return a set of common abbreviations that contain periods"""
    return {
        "mr.",
        "mrs.",
        "ms.",
        "dr.",
        "prof.",
        "sr.",
        "jr.",
        "etc.",
        "e.g.",
        "i.e.",
        "vs.",
        "v.",
        "fig.",
        "st.",
        "ave.",
        "inc.",
        "ltd.",
        "co.",
        "corp.",
        "ph.d.",
        "m.d.",
        "b.a.",
        "m.a.",
        "p.m.",
        "a.m.",
        "u.s.a.",
        "u.k.",
        "u.n.",
        "vol.",
    }
